# -- Layout --------------------------------------------------------------
# Only overrides not present in ~/.local/share/caelestia/
dwindle {
    pseudotile = true
}

general {
    resize_on_border = true
}

# -- Float Rules ---------------------------------------------------------
windowrule = float true, match:class nm-connection-editor
windowrule = size 60% 65%, match:class nm-connection-editor
windowrule = center 1, match:class nm-connection-editor

windowrule = float true, match:class org.gnome.Calculator
windowrule = size 380 600, match:class org.gnome.Calculator
windowrule = center 1, match:class org.gnome.Calculator

windowrule = float true, match:class xdg-desktop-portal-gtk
windowrule = size 70% 75%, match:class xdg-desktop-portal-gtk
windowrule = center 1, match:class xdg-desktop-portal-gtk
