; dawn — pagi-pagi sebelum kopi kedua
; best for: 06:00–09:00, slow warm start
[general]
temp-day=5000
temp-night=3500
gamma=0.80
fade=1
duration=3600
location-provider=manual
adjustment-method=wayland

[manual]
lat=-6.2
lon=106.8
