; morning - soft warm start, not too yellow
; best for: 05:30-09:30
[general]
temp-day=5000
temp-night=3600
gamma=0.88
fade=1
location-provider=manual
adjustment-method=wayland

[manual]
lat=-6.2
lon=106.8
