; reading - comfortable long reading mode
; best for: docs, browser, writing sessions
[general]
temp-day=4800
temp-night=3400
gamma=0.86
fade=1
location-provider=manual
adjustment-method=wayland

[manual]
lat=-6.2
lon=106.8
